################################################################################
#                                                                              #
#    Original    :  https://github.com/ioerror/duraconf                        #
#    Edits by    :  Danny Hyde                                                 #
#    Email       :  danny@dannyhyde.co.uk                                      #
#    Version     :  0.1                                                        #
#    Date        :  2023-11-15                                                 #
#    File        :  gpg-agent.conf                                             #
#    Location    :  $HOME/.local/share/gnupg/gpg-agent.conf                    #
#    Commentary  :                                                             #
#        This is my GnuPG configuration file. This is an implementation        #
#        of the riseup openpgp best practices.                                 #
#    References  :                                                             #
#        https://riseup.net/en/gpg-best-practices                              #
#                                                                              #
################################################################################

# enable ssh use

enable-ssh-support

# cache passphrase for N sconds (set to 1 week)
# will last session, but not survive reboot.

default-cache-ttl 604800
max-cache-ttl 604800

default-cache-ttl-ssh 604800
max-cache-ttl-ssh 604800

# set pinentry program

pinentry-program /usr/bin/pinentry-curses
