#!/bin/env bash ################################################################
#
#    Author      : Danny Hyde
#    Email       : danny@dannyhyde.co.uk
#    Version     : 0.2
#    Date        : 2023-12-25
#    File        : profile
#    Location    : $HOME/.config/shell/profile
#    Commentary  :
#        This would be the equivlant to a bashrc or zshrc, but I sometimes
#        switch between the two shell envioronments, so I've seperated what I
#        can.
#
################################################################################

# if not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

#################################     ENV     ##################################

[ -f "$HOME/.config/shell/env" ] && source "$HOME/.config/shell/env"

#################################     PATH     #################################

export PATH="$HOME/.local/bin:$PATH"
for d in "$HOME/.local/bin/"; do
	PATH="$d:$PATH"
done

export PATH="$PATH:$GOPATH/bin"


###########################     DEFAULT PROGRAMS     ###########################

export VISUAL="nvim"
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="w3m"


##########################     OPTIONAL SETTINGS     ###########################

set -o vi

HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=ignoredups
shopt -s histappend
shopt -s autocd


################################     PROMPT     ################################

#     GPG SSH AGENT     #

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null


alias dots="/usr/bin/git --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME"


# vim:tw=80:
